### PR TITLE
Updated for core24 and GNOME 46

### PR DESCRIPTION
**Pull request by kenvandine**
This is a WIP branch, it builds against gnome-46-2404-sdk and depends on the experimental gnome extension for core24

To build:
```
SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS=1 snapcraft 
```

### CODE REVIEW

**Comment by jssotomdz** [comment]
Seems straightforward, waiting for the extension to be stable to merge right?

**Review by sergio-costas — APPROVED** [review]
Looks straightforward.

**Comment by jssotomdz** [comment]
need to re-trigger the ci job here. might need to add that to the yml to make it easier

**Review by jssotomdz — APPROVED** [review]
ready to merge

**Pull request merged**
